In [1]:
## Matrix Operaitons
## Initializing an array
import numpy as np
X1 = np.array([[5,1],[4,2]])
Y1 = np.array([[21,32],[11,13]])
#matrix additon

Z1 = X1+Y1
print(Z1)

[[26 33]
 [15 15]]


In [2]:
# Addition using np.add function
Z2 = np.add(X1,Y1)
print(Z2)

[[26 33]
 [15 15]]


In [3]:
## Multiplicaiton by a scalar

X2 = np.array([[5,1],[4,5]])
X3 = 2*X2
print(X3)

[[10  2]
 [ 8 10]]


In [4]:
## Matrix Subtraction

S = Y1-X1
print(S)

[[16 31]
 [ 7 11]]


In [5]:
## Matrix Multiplication  # this is not actual matrix multiplicaiton
## Thisi is element-wise multiplicaiton

M = Y1*X1
print(M)

[[105  32]
 [ 44  26]]


In [6]:
## All the above element-wise , this is element-wise operaiton carried out in NumPy array

## Division
D  = X1/Y1
print(D)

[[0.23809524 0.03125   ]
 [0.36363636 0.15384615]]


In [7]:
## Exponential

E = X1**Y1
print(E)

[[1299066613          1]
 [   4194304       8192]]


In [8]:
### Matrix Multiplication   
## Matrix multiplication of mxn array with pxq array can be done only when n == p  and result matrix is the shape of (m,q)

In [9]:
x1 = np.arange(0,9).reshape(3,3)
y1 = np.arange(10,19).reshape(3,3)
MM = np.dot(x1,y1)                    # dot funciton in Numpy does the actual matrix multiplication
print(MM)

[[ 45  48  51]
 [162 174 186]
 [279 300 321]]


In [10]:
## Matrix Transpose

MT = MM.T        #'.T' gives transpose of matrix
print(MT)

[[ 45 162 279]
 [ 48 174 300]
 [ 51 186 321]]


In [11]:
## Alternative way for matrix transpose
MT1 = np.transpose(MM)
print(MT1)                  # transpose means , converting rows into column and columns into rows

[[ 45 162 279]
 [ 48 174 300]
 [ 51 186 321]]


In [12]:
## Let's take an example of matrix multiplication

## [1,2][3,4] [[1*3+2*7],[1*4+2*8]]  [17,22]
## [5,6][7,8] [[5*3+6*7],[5*4+6*8]]  [57,68]

# Let's see here

A = np.array([[1,2],[5,6]])
B = np.array([[3,4],[7,8]])
C = np.dot(A,B)
print(C)

[[17 20]
 [57 68]]


In [13]:
## Matrix Inverse 
from scipy import linalg as la

In [14]:
SLM = np.array([[5,6],[7,5]])
SLM

array([[5, 6],
       [7, 5]])

In [15]:
la.inv(SLM)

array([[-0.29411765,  0.35294118],
       [ 0.41176471, -0.29411765]])

Matrix Inverse -::- https://mathworld.wolfram.com/MatrixInverse.html