Linear Equation ==> ax+by = c (x,y) are unknown  (a,b,c) are values

For Example, suppose we want to solve the following simultaneous equation
- 5x+y+3z = 7
- 2x+4y+6z = 4
- x+5y+2z =5

In [ ]:
# We can translate into preceding set of equations into a matrix form, as follows

# [[5,1,3]     [[x]      [[7]
#  [2,4,6]      [y]  =    [4]
#  [1,5,2]]     [z]]      [5]]

# This is of the form Ax = b
# so, x = inv(A)*b

In [1]:
import numpy as np
from scipy import linalg as la

In [2]:
A = [[5,1,3],[2,4,6],[1,5,2]]
B = [[7],[4],[5]]
# Multiply inv of A with B vector

X = np.dot(la.inv(A),B)
print(X)

[[ 1.46666667]
 [ 0.86666667]
 [-0.4       ]]


In [3]:
# How to solve using sciPy 'SOLVE' function
la.solve(A,B)         # this is similat to scipy.linalg.solve(A,B)

array([[ 1.46666667],
       [ 0.86666667],
       [-0.4       ]])

In [ ]:
#### Calculating determent of matrix

# DM = [[5 1 3]
#      [2 4 6]
#      [1 5 2]]

# |A| = 5|4 6|-1|2 6|+3|2 4|
#        |5 2|  |1 2|  |1 5|
#|A| = 5(4*2 + 5*6)-**************

In [4]:
DM = [[5,1,3],[2,4,6],[1,5,2]]
la.det(A)

-90.0

In [ ]:
# Daterminent plays a major value in matrix inverse 