The null space of an MxN matrix A, denotes as null A, is the set of all solutions for the homogeneous Equation Ax = 0.

Calculating the null space of a matrix helps us in identifying all the potential values of x that help to solve 
the equation Ax =0.

In [1]:
import numpy as np
import sympy

In [2]:
## Initialize the matrix

M = sympy.Matrix([[1,2,3,0,0],[4,10,0,0,1]])
print(M)

Matrix([[1, 2, 3, 0, 0], [4, 10, 0, 0, 1]])


In [3]:
# Calculate the null space by using the null space funciton

M.nullspace()

[Matrix([
 [-15],
 [  6],
 [  1],
 [  0],
 [  0]]),
 Matrix([
 [0],
 [0],
 [0],
 [1],
 [0]]),
 Matrix([
 [   1],
 [-1/2],
 [   0],
 [   0],
 [   1]])]

In [4]:
x1 = [[-15],[6],[1],[0],[0]]

The Matrix multiplication of M and x1 will be perfomred as follows

In [5]:
np.dot(np.array(M),x1)

array([[0],
       [0]], dtype=object)

In [6]:
## Calculating range of Matrix

M1 = np.array([[3,300],[4,400]]) #Range of a matrix is ideally the maximun and minimum in the given array of elements
R = np.ptp(M1)   #maximun value in matrix - minimum value in matrix -::-  400 - 3 = 397 
R

397

In [7]:
## Range of elements in the rows of a matrix
RR = np.ptp(M1,axis=0)
print(RR)
## Range of elements in the columns of a matrix
CR = np.ptp(M1,axis=1)     #ptp stands for peak to peak 
print(CR)

[  1 100]
[297 396]


## Calculating the rank and nullity of a matrix

The rank of a matrix is defined as the maximum number of linear independent column vectors in the matrix or the 
maximum number of linear independent row vectors in the matrix.

In [8]:
C = np.array([[3,2,-1],[2,-3,-5],[-1,-4,-3]])
print(C)

[[ 3  2 -1]
 [ 2 -3 -5]
 [-1 -4 -3]]


Transforming matrix C
[[1,4,3],[0,1,1],[0,0,0]]

Given that two rows out of the three rows have at least one non-zero elements in the matrix , the rank of the matrix is 2

In [9]:
np.linalg.matrix_rank(C)

2

Rank of Matrix -::- https://stattrek.com/matrix-algebra/matrix-rank.aspx

## Calculating the nullity of a matrix

Nullity of a matrix is the difference between the number of columns and the rank of the matrix

In [10]:
C.shape

(3, 3)

In [11]:
C.shape[1]

3

In [12]:
C.shape[1] - np.linalg.matrix_rank(C)

1

So, the nullity of the matrix C is 1