In the linear algebra, a square matrix A is diadonalizable if it is similar to a diagonal matrix, that is , if there exists an inversable matrix P such that inv(P)AP is a diagonal matrix

In [1]:
import numpy as np
#Initialize 1D array
A1_1D = np.array([1,2,3])
print(A1_1D)

[1 2 3]


In [2]:
DiaM = np.diag(A1_1D)
DiaM

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [3]:
# Consider Eigen vector of the given matrix as P matrix
from scipy import linalg as la    # similar import scipy.linalg as la
p,v = la.eig(DiaM)
print(p,'\n',v)

[1.+0.j 2.+0.j 3.+0.j] 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


The matrix 'v' would be the eigen vector ( which is the p matrix for us)

In [4]:
#Calculating inv(v)*DiaM*v

np.dot(np.dot(np.linalg.inv(v),DiaM),v)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [5]:
# Diagonalizing eigen values of our matrix is done as follows
np.diag(p)

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 2.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 3.+0.j]])

In [6]:
np.dot(np.dot(np.linalg.inv(v),DiaM),v) - np.diag(p)

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In the preceding calculations, note that the difference between the two outputs is zero and ,hence, satisfies our originally laid objective; inv(p)*A*p is a diagonal matrix