A square matrix 'A' can be decomposed into two square matrices L and U such that A = LU where U is an upper triangular matrix formed as result of applying Gauss elimination method on A. L is a lower triangular matrix with diagonal elements being equal to 1

In [ ]:
A  [[a11 a12 a13]     L = [[1   0   0]     U = [[U11 U12 U13]
    [a21 a22 a23]          [L21 1   0]          [0   U22 U23]            such that A = LU
    [a31 a32 a33]]         [L31 L32 1]]         [0   0   U33]    

In [1]:
#define a matrix
import numpy as np
import scipy as s

In [2]:
M = np.array([[3.,1.,1.],[1.,2.,3.],[1.,0,0]])
print(M)

[[3. 1. 1.]
 [1. 2. 3.]
 [1. 0. 0.]]


In [4]:
# Import linalg 
import scipy.linalg as la
P,L,U = la.lu(M)
print(P,'\n\n',L,'\n\n',U)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

 [[ 1.          0.          0.        ]
 [ 0.33333333  1.          0.        ]
 [ 0.33333333 -0.2         1.        ]] 

 [[3.         1.         1.        ]
 [0.         1.66666667 2.66666667]
 [0.         0.         0.2       ]]


http://faculty.etsu.edu/joynerm/Diagonal%20Matrices.pdf

https://www.math-only-math.com/triangular-matrix.html

In [5]:
np.dot(L,U)  #multiply Lower and upper , gives us original matrix 'M' [2]

array([[3.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 2.00000000e+00, 3.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 5.55111512e-17]])

#### Calculating the QR decompostion of the Matrix

Similar to the LU decompostion, QR decompostion is the decompostion of an original matrix into it's constituent parts, the matrix A= QR , where Q is an orthogonal matrix and R is an upper triangular matrix.

let's look into the properties of orthogonal matrix 
 - it's a square matrix
 - Multiplying Q with it's transpose results in identity matrix

In [6]:
# Initialize the matrix

MM = np.array([[3.,1.,1.],[1.,2.,3.],[1.,0.,0.]])
print(MM)

[[3. 1. 1.]
 [1. 2. 3.]
 [1. 0. 0.]]


In [7]:
#Extract Q and R matrices of the martix MM

Q,R = la.qr(MM)
print(Q,'\n\n',R)

[[-0.90453403  0.22019275 -0.36514837]
 [-0.30151134 -0.9358192   0.18257419]
 [-0.30151134  0.27524094  0.91287093]] 

 [[-3.31662479 -1.50755672 -1.80906807]
 [ 0.         -1.65144565 -2.58726485]
 [ 0.          0.          0.18257419]]


In [8]:
# Multiply Q with it's transpose results in an identity matrix

print(np.dot(Q,Q.T))

[[ 1.00000000e+00 -1.20065498e-16 -1.22552319e-16]
 [-1.20065498e-16  1.00000000e+00 -1.95722499e-17]
 [-1.22552319e-16 -1.95722499e-17  1.00000000e+00]]


In [9]:
# Matrix multiplication Q and R to get original matrix MM
print(np.dot(Q,R))

[[ 3.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00  2.00000000e+00  3.00000000e+00]
 [ 1.00000000e+00 -1.11022302e-16 -1.72860033e-16]]
