In [ ]:
The Eigen vector of a given vector is the vector that satisfies the following conditiond 

A.v = λ.v

A --> Matrix of our interest 
v --> Eigen vector
λ --> Eigen value

In [1]:
import numpy as np
A = np.array([[3,4],[5,6]])
print(A)

[[3 4]
 [5 6]]


In [2]:
#Calculating the eigen values and eigen vectors

In [3]:
import scipy.linalg as LA
la,v = LA.eig(A)
print(la,'\n\n',v)

[-0.21699057+0.j  9.21699057+0.j] 

 [[-0.77925158 -0.54107946]
 [ 0.62671124 -0.84097147]]


In [ ]:
la --> eigen value
v  --> eigen vector

In [4]:
# Calculate the value of the matrix multiplicaiton λ.v

la*v

array([[ 0.16909024-0.j, -4.98712427+0.j],
       [-0.13599043+0.j, -7.75122614+0.j]])

In [5]:
# Calculate the value of the matrix multiplicaiton A.v
np.dot(A,v)

array([[ 0.16909024, -4.98712427],
       [-0.13599043, -7.75122614]])

Note -::-  The output satisfies the initial laid equation :: A.v  = λ.v