The SVD of a matrix A is the decomposition or factorization of A into the product of the three matrices.

A = UxΣxV

The size of the individual matrices is as follows , if you know that matrix A is of size MxN

1. Matrix U is of size MxM
2. Matrix V is of size NXN
3. Matrix Σ is of size MxN

In [1]:
# Initialize an array
import numpy as np
S = np.array([[5,6],[1,2]])
S

array([[5, 6],
       [1, 2]])

In [2]:
import scipy.linalg as la

#Use the svd function to calculate the SVD matrices ( U , V and Σ)

la.svd(S)

(array([[-0.96301285, -0.26945546],
        [-0.26945546,  0.96301285]]),
 array([8.10904919, 0.49327608]),
 array([[-0.62701799, -0.77900477],
        [-0.77900477,  0.62701799]]))

In [3]:
U = np.array([[-0.96301285, -0.26945546],
        [-0.26945546,  0.96301285]])

Sigma = np.array([[8.10904919,0],[0,0.49327608]])

V = np.array([[-0.62701799, -0.77900477],
        [-0.77900477,  0.62701799]])

In [4]:
# perform the matrix multiplication of U , Sigma and V matrices

np.dot(np.dot(U,Sigma),V)

array([[4.99999998, 5.99999994],
       [1.00000003, 2.00000002]])

Sigma value decomposition is more useful technique in typical data science 

one of the most important application SVd is recommended system where the matrix of user item is broken into multiple matrices that are simplier to implement. 

Similarly SVD is used in Image compression algorithm where we try to capture the information by using very few pixels as possible.